#pragma once
#pragma once

// Byte address buffers
#define RHIDX12_BINDLESS_DESCRIPTOR_SPACE 1

#define RHIDX12_SRV_REGISTER 0
#define RHIDX12_SAMPLER_STATE_REGISTER 0          

#define RHIDX12_FIXED_CBV_REGISTER_0 0
#define RHIDX12_FIXED_CBV_REGISTER_1 1
#define RHIDX12_FIXED_CBV_REGISTER_2 2
#define RHIDX12_FIXED_CBV_REGISTER_3 3
#define RHIDX12_FIXED_CBV_REGISTER_4 4
#define RHIDX12_FIXED_CBV_REGISTER_5 5
#define RHIDX12_FIXED_CBV_REGISTER_6 6
#define RHIDX12_FIXED_CBV_REGISTER_7 7

#define RHIDX12_EMU_SPECCONST_CBV_VS_REGISTER 8
#define RHIDX12_EMU_SPECCONST_CBV_HS_REGISTER 9
#define RHIDX12_EMU_SPECCONST_CBV_DS_REGISTER 10
#define RHIDX12_EMU_SPECCONST_CBV_GS_REGISTER 11
#define RHIDX12_EMU_SPECCONST_CBV_PS_REGISTER 12

#define RHIDX12_ROOT_CONSTANT_CBV_REGISTER 13

#define RHIDX12_EMU_DRAWINDEX_CBV_VS_DESCRIPTOR_SPACE 2
#define RHIDX12_EMU_DRAWINDEX_CBV_VS_REGISTER 0


#define RHIDX12_EMU_BLITIMAGE_DESCRIPTOR_SPACE 0
#define RHIDX12_EMU_BLITIMAGE_SRV_REGISTER 0
#define RHIDX12_EMU_BLITIMAGE_SAMPLER_STATE_REGISTER 0
