name: Windows Build (MSVC/ClangCL)
permissions:
  contents: read

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc, clang-cl]
        build_type: [Release]

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: latest
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      - name: Configure CMake
        shell: pwsh
        run: |
          if (${{ matrix.compiler }} -eq "msvc") {
              Write-Host "Configuring for MSVC"
              cmake -B build `
                -DCMAKE_POLICY_VERSION_MINIMUM=3.5 `
                -DCMAKE_C_COMPILER=cl `
                -DCMAKE_CXX_COMPILER=cl `
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
                -DPYRO_COMMON_BUILD_TESTS=OFF `
                -DPYRO_COMMON_SHARED_LIBRARY=OFF `
                -DPYRO_RHI_BUILD_VULKAN=ON `
                -DPYRO_RHI_BUILD_DX12=ON `
                -DPYRO_RHI_BUILD_METAL=OFF `
                -S .
          } elseif (${{ matrix.compiler }} -eq "clang-cl") {
              Write-Host "Configuring for ClangCL"
              cmake -B build `
                -DCMAKE_POLICY_VERSION_MINIMUM=3.5 `
                -DCMAKE_C_COMPILER=clang-cl `
                -DCMAKE_CXX_COMPILER=clang-cl `
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
                -DPYRO_COMMON_BUILD_TESTS=OFF `
                -DPYRO_COMMON_SHARED_LIBRARY=OFF `
                -DPYRO_RHI_BUILD_VULKAN=ON `
                -DPYRO_RHI_BUILD_DX12=ON `
                -DPYRO_RHI_BUILD_METAL=OFF `
                -S .
          }

      - name: Build
        shell: pwsh
        run: cmake --build build --config ${{ matrix.build_type }} --parallel 4

      - name: Run API validation tests
        shell: pwsh
        working-directory: build
        run: ctest --build-config ${{ matrix.build_type }} --rerun-failed --output-on-failure
