name: DirectX12 Validation (Windows MSVC)
permissions:
  contents: read

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake (MSVC)
        run: >
          cmake -B build
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DPYRO_COMMON_BUILD_TESTS=OFF
          -DPYRO_COMMON_SHARED_LIBRARY=OFF
          -DPYRO_RHI_BUILD_TESTS=ON
          -DPYRO_RHI_BUILD_VULKAN=OFF
          -DPYRO_RHI_BUILD_VULKAN_VALIDATION_TESTS=OFF
          -DPYRO_RHI_BUILD_DX12=ON
          -DPYRO_RHI_BUILD_DX12_VALIDATION_TESTS=ON
          -DPYRO_RHI_BUILD_METAL=OFF
          -S .

      - name: Build (MSVC)
        run: cmake --build build --config ${{ matrix.build_type }} --parallel 4
        
      - name: Run DX12 tests
        working-directory: build
        run: ctest --build-config ${{ matrix.build_type }} --output-on-failure --rerun-failed