name: Windows Build (MSVC)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
            vulkan-query-version: latest
            vulkan-components: Vulkan-Headers, Vulkan-Loader
            vulkan-use-cache: true
      - name: Configure CMake (MSVC)
        run: >
          cmake -B build
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          -DCMAKE_C_COMPILER=cl
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DPYRO_COMMON_BUILD_TESTS=OFF
          -DPYRO_COMMON_SHARED_LIBRARY=OFF
          -S .

      - name: Build (MSVC)
        run: cmake --build build --config ${{ matrix.build_type }} --parallel 4
